---
title: "DEGs_TranscriptType"
output: html_notebook
---


```{r}
# Loading packages
library(BiocManager)
library(biomaRt)
library (plyr);
```

```{r warning=FALSE}
# loading data
setwd("~/Documents/TFM/GitHub/HB_PublicData/1-Obtaining-DEGs-for-HB/Outputs_HB/")
DEGs <- read.csv("HB_db_DEG.csv")
```


**Accessing Ensembl annotation with biomaRt:**
https://www.bioconductor.org/packages/devel/bioc/vignettes/biomaRt/inst/doc/accessing_ensembl.html

* Database: Ensembl Genes 104
* Dataset: Human genes (GRCh38)
* Filters: Gene - Gene Name(s) - hgnc_symbol
* Attributes - Transcript Types - transcript-biotype
```{r warning=FALSE}
# describe dataset
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
```

```{r warning=FALSE}
# add transcript type 
genes <- list(DEGs$gene)
trans_type <- getBM(attributes <- c('hgnc_symbol','transcript_biotype'), filters <- 'hgnc_symbol', values <- genes, mart <- ensembl)
```

```{r}
#export types
write.csv(trans_type, "DEGs_transcript_type.csv", row.names = FALSE)
```

```{python}
import pandas as pd
trans_type = pd.read_csv('DEGs_transcript_type.csv')
trans_type.transcript_biotype.value_counts()
```
```{python}
import pandas as pd
trans_type = pd.read_csv('DEGs_transcript_type.csv', index_col=0)
only_coding_lst = trans_type.loc[trans_type['transcript_biotype'].isin(['protein_coding'])].index.tolist()
```

```{python}
non_coding = trans_type[~trans_type.index.isin(only_coding_lst)]
non_coding.to_csv("DEGs_non_coding.csv")
print(len(set(non_coding.index.tolist())))
```
