#!/bin/bash
set -euo pipefail

# Defining default values for parameters
DESeq2_padj=0.05
DESeq2_LFC=1
RRA_Score=0.05
waddR_resolution=0.001
waddR_permnum=10000
multiXrank_r=0.5
multiXrank_selfloops=0
multiXrank_delta=0.5
Molti_modularity=1
Molti_Louvain=0

# Usage function
usage(){
echo -e '\n'
echo "usage: multiAffinity [-h] -c COUNTS_PATH -m METADATA_PATH -n NETWORK_PATH"
echo "                     [-a DESeq2_padj] [-b DESeq2_LFC] [-d RRA_Score]"
echo "                     [-e waddR_resolution] [-f waddR_permnum] [-g multiXrank_r]"
echo "                     [-h multiXrank_selfloops] [-i multiXrank_delta]"
echo "                     [-j Molti_modularity] [-k Molti_Louvain]"
echo -e '\n'
echo "arguments:"
echo "    -h                          show this help message and exit"
echo "    -c COUNTS_PATH              path to counts matrix, single or multiple (-c COUNTS_PATH1,COUNTS_PATH2)"
echo "    -m METADATA_PATH            path to metadata, single or multiple (-c METADATA_PATH1,METADATA_PATH2)"
echo "    -n NETWORK_PATH             path to network, single or multiple (-c NETWORK_PATH1,NETWORK_PATH2)"
echo "    -a DESeq2_padj              optional - default value is 0.05"
echo "    -b DESeq2_LFC               optional - default value is 1"
echo "    -d RRA_Score                optional - default value is 0.05"
echo "    -e waddR_resolution         optional - default value is 0.001"
echo "    -f waddR_permnum            optional - default value is 10000"
echo "    -g multiXrank_r             optional - default value is 0.5"
echo "    -h multiXrank_selfloops     optional - default value is 0"
echo "    -i multiXrank_delta         optional - default value is 0.05"
echo "    -j Molti_modularity         optional - default value is 1"
echo "    -k Molti_Louvain            optional - default value is 0"
echo " "
exit 0
} 
                
# Classifying input arguments
while getopts ":hc:m:n:a:b:d:e:f:g:h:i:j:k:" opt; do
  case $opt in
    h) usage                             ;;
    c) set -f
       IFS=','
       counts=($OPTARG)                  ;;
    m) set -f
       IFS=','
       metadata=($OPTARG)                ;;
    n) set -f
       IFS=','
       network=($OPTARG)                 ;;
    a) DESeq2_padj=($OPTARG)             ;;
    b) DESeq2_LFC=($OPTARG)              ;;
    d) RRA_Score=($OPTARG)               ;;
    e) waddR_resolution=($OPTARG)        ;;
    f) waddR_permnum=($OPTARG)           ;;
    g) multiXrank_r=($OPTARG)            ;;
    h) multiXrank_selfloops=($OPTARG)    ;;
    i) multiXrank_delta=($OPTARG)        ;;
    j) Molti_modularity=($OPTARG)        ;;
    k) Molti_Louvain=($OPTARG)           ;;
  esac
done

# Defining mandatory arguments
if [ -z ${counts+x} ]; then echo "-c is obligatory"; exit 1; fi
if [ -z ${metadata+x} ]; then echo "-m is obligatory"; exit 1; fi
if [ -z ${network+x} ]; then echo "-n is obligatory"; exit 1; fi

# Creating input directories and organizing data
mkdir -p input; mkdir -p input/layers; mkdir -p input/data; mkdir -p input/data/counts; mkdir -p input/data/metadata
for i in "${counts[@]}"; do mv ${i} input/data/counts; done
for i in "${metadata[@]}"; do mv ${i} input/data/metadata; done
for i in "${network[@]}"; do mv ${i} input/layers; done

echo 'STEP1 - Finding metaDEGs'
bash bin/metaDEGs/run_metaDEGs.sh $DESeq2_padj $DESeq2_LFC $RRA_Score $waddR_resolution $waddR_permnum

echo 'STEP2 - Perform affinity study'
bash bin/Affinity/run_Affinity.sh $multiXrank_r $multiXrank_selfloops $multiXrank_delta

echo 'STEP3 - Analysing DEGs in network communities' #(if you you want to check optimal number randomizations, go to Communities/Communities.md)
bash bin/Communities/run_Communities.sh $Molti_modularity $Molti_Louvain

python bin/join_output.py
echo 'multiAffinity completed. Check out the output folder'
